// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avrorepo.proto

package main.java.proto;

public final class avrorepo {
  private avrorepo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DeviceState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DeviceState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SaveDeviceStateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SaveDeviceStateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SaveDeviceStateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SaveDeviceStateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016avrorepo.proto\022\005proto\032\037google/protobuf" +
      "/timestamp.proto\"\236\001\n\013DeviceState\022\020\n\010devi" +
      "ceId\030\002 \001(\t\022\023\n\013namespaceId\030\001 \001(\t\022\014\n\004date\030" +
      "\003 \001(\t\022\025\n\rreportedState\030\005 \001(\014\022\024\n\014desiredS" +
      "tate\030\006 \001(\014\022-\n\ttimestamp\030\007 \001(\0132\032.google.p" +
      "rotobuf.Timestamp\"J\n\026SaveDeviceStateRequ" +
      "est\022\020\n\010deviceId\030\001 \001(\t\022\036\n\002ds\030\002 \001(\0132\022.prot" +
      "o.DeviceState\")\n\027SaveDeviceStateResponse" +
      "\022\016\n\006status\030\001 \001(\0102^\n\tAvrorepos\022Q\n\016SetDevi" +
      "ceState\022\035.proto.SaveDeviceStateRequest\032\036" +
      ".proto.SaveDeviceStateResponse\"\000B\035\n\017main" +
      ".java.protoB\010avrorepoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_proto_DeviceState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_DeviceState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DeviceState_descriptor,
        new java.lang.String[] { "DeviceId", "NamespaceId", "Date", "ReportedState", "DesiredState", "Timestamp", });
    internal_static_proto_SaveDeviceStateRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_SaveDeviceStateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SaveDeviceStateRequest_descriptor,
        new java.lang.String[] { "DeviceId", "Ds", });
    internal_static_proto_SaveDeviceStateResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_SaveDeviceStateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SaveDeviceStateResponse_descriptor,
        new java.lang.String[] { "Status", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
