// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avrorepo.proto

package main.java.proto;

public interface DeviceStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.DeviceState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string deviceId = 2;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string deviceId = 2;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>string namespaceId = 1;</code>
   * @return The namespaceId.
   */
  java.lang.String getNamespaceId();
  /**
   * <code>string namespaceId = 1;</code>
   * @return The bytes for namespaceId.
   */
  com.google.protobuf.ByteString
      getNamespaceIdBytes();

  /**
   * <code>string date = 3;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string date = 3;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>bytes reportedState = 5;</code>
   * @return The reportedState.
   */
  com.google.protobuf.ByteString getReportedState();

  /**
   * <code>bytes desiredState = 6;</code>
   * @return The desiredState.
   */
  com.google.protobuf.ByteString getDesiredState();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 7;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 7;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
}
